[package]
name = "sublet"
version = "0.3.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-std = "1.12.0"
reqwest = "0.12.3"
serde = "1.0.197"
toml = "0.8.12"
zip = "0.6.6"
